application: gae-python-django
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /pub/css
  static_dir: pub/css

- url: /pub/js
  static_dir: pub/js

- url: /pub/img
  static_dir: pub/img

- url: /pub/font
  static_dir: pub/font

- url: /admin/.*
  script: google.appengine.ext.admin.application
  login: admin

- url: .*
  script: main.application

libraries:
- name: django
  version: "1.5"

builtins:
- remote_api: on
